### ISSUE TITLE
Use AutoFac instead of StructureMap

### ISSUE THREAD

**Issue by TDK1964** [jbogard/ContosoUniversity#22]
Any of you clever chaps ever done this?
I use AF in all my projects and would really like to see an AF version.

**Comment by alonam** [comment]
Yes, I did.

**Comment by alonam** [comment]
here's my mediator module: https://gist.github.com/AlonAmsalem/b76efecb436fbb1a67add18de1f85a69

**Comment by TDK1964** [comment]
@AlonAmsalem Thanks for this, very useful. Have you managed to convert other classes in the project?

[HtmlHelperExtensions.cs](https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Infrastructure/HtmlHelperExtensions.cs)

And this one [MvcTransactionFilter.cs](https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Infrastructure/DataAccess/MvcTransactionFilter.cs)

**Comment by alonam** [comment]
Here's how I implemented the transaction-filter

``` csharp
public class TransactionFilter : IAutofacActionFilter
    {
        public void OnActionExecuting(HttpActionContext actionContext)
        {
            var requestScope = actionContext.Request.GetDependencyScope();

            var context = requestScope.GetService(typeof(CloudinatorContext)) as CloudinatorContext;

            context?.BeginTransaction();
        }

        public void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
        {
            var requestScope = actionExecutedContext.Request.GetDependencyScope();

            var context = requestScope.GetService(typeof(CloudinatorContext)) as CloudinatorContext;

            context?.CloseTransaction(actionExecutedContext.Exception);
        }
    }
```

**Comment by alonam** [comment]
I don't use the Html-Helper-Extensions because my client-side is a standalone AngularJS

**Comment by alonam** [comment]
Here's my Global.asax, you'll need it for the transaction-filter

``` csharp
    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            var container = IoC.Initialize();

            GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(container);

            GlobalConfiguration.Configure(WebApiConfig.Register);

            AutoMapperBootstrapper.Initialize(container);

            AreaRegistration.RegisterAllAreas();
        }
    }
```

**Comment by TDK1964** [comment]
```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
        {
            var library =
                StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<HtmlConventionLibrary>();
            return ElementGenerator<T>.For(library, t => StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance(t), model);
        }
```

I'm still having problems converting this to Autofac. I tried this but it doesn't work.

```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
        {
            var library = AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve<HtmlConventionLibrary>();
            return ElementGenerator<T>.For(library, t => AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve(t), model);
        }
```
